import createConnection from '../index'

async function create() {
  const connection = await createConnection()

  await connection.query(`truncate migrations`)
  await connection.query(`drop table posicoes`)
  await connection.query(`drop table plantas`)
  await connection.query(`drop table unidades`)
  await connection.query(`drop table documentos_digitais_campos`)
  await connection.query(`drop table documentos_digitais`)
  await connection.query(`drop table campos_documento`)
  await connection.query(`drop table versoes_documento`)
  await connection.query(`drop table rastreamento_documentos`)
  await connection.query(`drop table documentos`)
  await connection.query(`drop table rastreamento_volumes`)
  await connection.query(`drop table volumes`)
  await connection.query(`drop table times_coleta`)
  await connection.query(`drop table coletas`)
  await connection.query(`drop table entregadores`)
  await connection.query(`drop table veiculos`)
  await connection.query(`drop table afastamentos`)
  await connection.query(`drop table escalas`)
  await connection.query(`drop table jornadas`)
  await connection.query(`drop table pessoas`)
  await connection.query(`drop table funcoes`)
  await connection.query(`drop table servicos_contratados`)
  await connection.query(`drop table frequencia_coletas`)
  await connection.query(`drop table pontos_coleta`)
  await connection.query(`drop table tipos_documento`)
  await connection.query(`drop table contratos`)
  await connection.query(`drop table solicitantes`)
  await connection.query(`drop table departamentos`)
  await connection.query(`drop table clientes`)
  await connection.query(`drop table unidades_sla`)
  await connection.query(`drop table frequencias`)
  await connection.query(`drop table composicao_lotes`)
  await connection.query(`drop table tipos_afastamento`)
  await connection.query(`drop table status`)
  await connection.query(`drop table servicos`)
  await connection.query(`drop table cidades`)
  await connection.query(`drop table estados`)
  await connection.query(`drop table user_tokens`)
  await connection.query(`drop table menu_options`)
  await connection.query(`drop table modules`)
  await connection.query(`drop table navigation`)
  await connection.query(`drop table profile_options`)
  await connection.query(`drop table users_profiles`)
  await connection.query(`drop table profiles`)
  await connection.query(`drop table users`)
  await connection.query(`drop table block_reasons`)
  await connection.query(`drop table user_groups`)

  await connection.close()
}

create().then(() => console.log('Tabelas deletadas!'))
